services:

  jumarket-api:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '80:8080'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${DB_PORT}/${DB_NAME}'
      - 'SPRING_DATASOURCE_USERNAME=${DB_USERNAME}'
      - 'SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}'
    depends_on:
      - postgres


  postgres:
    image: 'postgres:14'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    ports:
      - '5432:${DB_PORT}'
