services:
  postgres:
    image: 'postgres:14'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    ports:
      - '5432:${DB_PORT}'
