CREATE SEQUENCE IF NOT EXISTS tb_categories_seq AS smallint INCREMENT BY 1 START 1;

CREATE TABLE IF NOT EXISTS tb_categories (
    id SMALLSERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
)